# Generated by Django 2.2.6 on 2019-10-14 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(default=1, help_text='Number of copies available for Members'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
    ]
