# Generated by Django 2.2.6 on 2019-10-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0002_auto_20191014_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagement.Member', verbose_name='Member'),
        ),
    ]
