# Generated by Django 2.2.6 on 2019-10-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0003_auto_20191014_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
    ]
