# Generated by Django 2.2.6 on 2019-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0004_remove_book_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(default=1, help_text='Number of copies available for Members'),
        ),
    ]
