# Generated by Django 2.2.6 on 2019-10-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0005_book_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book_returned',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Returned'),
        ),
    ]
