# Generated by Django 2.2.6 on 2019-10-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0007_auto_20191014_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
