# Generated by Django 2.2.6 on 2019-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0008_delete_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
