# Generated by Django 2.2.6 on 2019-10-15 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0009_auto_20191014_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
    ]
