# Generated by Django 2.2.6 on 2019-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0011_auto_20191015_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
