# Generated by Django 2.2.6 on 2019-10-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0012_borrow_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='book_returned',
        ),
    ]
