# Generated by Django 2.2.6 on 2019-10-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0013_remove_borrow_book_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='returned',
            new_name='book_returned',
        ),
    ]
