# Generated by Django 2.2.6 on 2019-10-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(help_text='Enter Hotel name', max_length=100, verbose_name='Name'),
        ),
    ]
