# Generated by Django 2.2.6 on 2019-10-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0002_auto_20191018_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter type of room', max_length=100, verbose_name='Category')),
                ('price', models.IntegerField(help_text='Enter the price', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Enter room number', verbose_name='Room No')),
                ('category', models.ForeignKey(help_text='Select category', on_delete=django.db.models.deletion.CASCADE, to='hotel_manement_system.Category', verbose_name='Category')),
            ],
        ),
    ]
