# Generated by Django 2.2.6 on 2019-10-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0003_category_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Guest name', max_length=100, verbose_name='Name')),
                ('phone_no', models.IntegerField(help_text='Enter phone number', verbose_name='Contact Number')),
                ('adhar_number', models.IntegerField(help_text='Enter adhar numbr', verbose_name='Adhar number')),
            ],
        ),
    ]
