# Generated by Django 2.2.6 on 2019-10-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0004_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter manager name', max_length=100, verbose_name='Manger name')),
                ('phone_number', models.IntegerField(help_text='Enter phone number', verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateField(help_text='select date', verbose_name='Check In date')),
                ('checkout_date', models.DateField(help_text='select date', verbose_name='Check out date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed Transaction')),
                ('is_canceled', models.BooleanField(default=False, help_text='select to cancel booking', verbose_name='Canceled')),
                ('guest', models.ForeignKey(help_text='Select guest', on_delete=django.db.models.deletion.CASCADE, to='hotel_manement_system.Guest', verbose_name='Guest name')),
                ('room_no', models.ForeignKey(help_text='Select room', on_delete=django.db.models.deletion.CASCADE, to='hotel_manement_system.Room', verbose_name='Room number')),
            ],
        ),
    ]
