# Generated by Django 2.2.6 on 2019-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0005_manager_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='people_count',
            field=models.IntegerField(default=1, help_text='Enter number of people', verbose_name='Total guest'),
        ),
    ]
