# Generated by Django 2.2.6 on 2019-10-18 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0006_record_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='checkin_date',
            field=models.DateField(default=datetime.date(2019, 10, 18), help_text='select date', verbose_name='Check In date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkout_date',
            field=models.DateField(default=datetime.date(2019, 10, 19), help_text='select date', verbose_name='Check out date'),
        ),
    ]
