# Generated by Django 2.2.6 on 2019-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0007_auto_20191018_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='yes_or_no',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Booking ID'),
        ),
    ]
