# Generated by Django 2.2.6 on 2019-10-19 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0008_auto_20191018_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.CharField(help_text='Enter the price', max_length=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkin_date',
            field=models.DateField(default=datetime.date(2019, 10, 19), help_text='select date', verbose_name='Check In date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkout_date',
            field=models.DateField(default=datetime.date(2019, 10, 20), help_text='select date', verbose_name='Check out date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Check out'),
        ),
    ]
