# Generated by Django 2.2.6 on 2019-10-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0009_auto_20191019_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='adhar_number',
            field=models.CharField(help_text='Enter adhar number', max_length=12, verbose_name='Adhar number'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_no',
            field=models.CharField(help_text='Enter phone number', max_length=10, verbose_name='Contact Number'),
        ),
    ]
