# Generated by Django 2.2.6 on 2019-10-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manement_system', '0010_auto_20191019_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Hotel',
            field=models.ForeignKey(help_text='Select manager hotel', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_manement_system.Hotel', verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number', max_length=10, verbose_name='Phone number'),
        ),
    ]
